[package]
name = "phie"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/phie"
description = "Experimental emulator of a processor that understands ùúë-calculus expressions"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/phie"
keywords = ["eolang", "compiler", "emulator", "oop"]
categories = ["command-line-utilities"]

[dependencies]
regex = "1.5.5"
lazy_static = "1.4.0"
rstest = "0.12.0"
assert_cmd = "2.0.4"
env_logger = "0.9.0"
hex = "0.4.3"
strum = "0.24.1"
strum_macros = "0.24.3"
itertools = "0.10.4"
arr_macro = "0.1.3"
log = "0.4.1"
simple_logger = "2.1.0"
ctor = "0.1.21"
