[package]
name = "eoc"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/yegor256/eoc"
description = "EO-to-binaries experimental compiler"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/yegor256/eoc"
keywords = ["eolang", "compiler", "emulator", "oop"]
categories = ["command-line-utilities"]

[dependencies]
regex = "1.5.4"
lazy_static = "1.4.0"
rstest = "0.12.0"
assert_cmd = "2.0.4"
env_logger = "0.9.0"
hex = "0.4.3"
strum = "0.23.0"
strum_macros = "0.23.1"
itertools = "0.10.3"
arr_macro = "0.1.3"
log = "0.4.1"
simple_logger = "2.1.0"
ctor = "0.1.21"
